<a href="https://colab.research.google.com/github/nihalsinghgujral/Flaapy-bird/blob/main/102003132_Dipsy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,6,4,5])



In [ ]:
result=arr[::-1]


In [ ]:
print("reverse array ",result)

reverse array  [5 4 6 3 2 1]


In [ ]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])

In [ ]:
flt=array1.flatten()
print("flatten array is",flt)

flatten array is [1 2 3 2 4 5 1 2 3]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(arr1)
print(arr2)
print("arr1=arr2",np.array_equal(arr1,arr2))


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
arr1=arr2 True


In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3,1])
x1=np.bincount(x)
max_ele=x1.argmax()
print("array x is",x)
print("max element is",max_ele)
for i in range(0,x.size):
  if x[i]==max_ele:
    print("indices are :",i)

print("array y is",y)
y1=np.bincount(y)
max_eley=y1.argmax()
print("max element is",max_eley)
for i in range(0,y.size):
  if y[i]==max_eley:
    print("indices are",i)    



  




array x is [1 2 3 4 5 1 2 1 1 1]
max element is 1
indices are : 0
indices are : 5
indices are : 7
indices are : 8
indices are : 9
array y is [1 1 1 2 3 4 2 4 3 3 1]
max element is 1
indices are 0
indices are 1
indices are 2
indices are 10


In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6')
gfg
print("sum of elements is ",np.sum(gfg))
print("column wise sum is",np.sum(gfg,axis=0))
print("row wise sum is",np.sum(gfg,axis=1))


sum of elements is  45
column wise sum is [[20  9 16]]
row wise sum is [[14]
 [16]
 [15]]


In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
n_array
print("diagonal elements ",np.diagonal(n_array))
print("sum of diagonal elements is ",np.trace(n_array))
w,v=np.linalg.eig(n_array)
print("eigen value is ",w)
print("eigen vector is ",v )
print("inverse is",np.linalg.inv(n_array))
print("determinant of array is",np.linalg.det(n_array))

diagonal elements  [55 44 77]
sum of diagonal elements is  176
eigen value is  [98.16835147 28.097044   49.73460452]
eigen vector is  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse is [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant of array is 137180.0000000001


In [ ]:
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
print("multiplication")
print(np.matmul(p,q))
print("covariance is ")
print(np.cov(p,q))

p1=np.array([[1,2],[2,3],[4,5]])
q1=np.array([[4,5,1],[6,7,2]])
print("multiplication")
print(np.matmul(p1,q1))




multiplication
[[16 19]
 [26 31]]
covariance is 
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
multiplication
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print("inner product is",np.inner(x,y))
print("outer product is ",np.outer(x,y))
print("cross product is ",np.cross(x,y))

inner product is [[17 52]
 [13 62]]
outer product is  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cross product is  [[-20   4   7]
 [-84  36  20]]


In [ ]:
#q2 a
array=np.array([[1,-2,3],[-4,5,-6]])
print("the absolute value element wise:")
print(abs(array))

print("25th percentile column wise")
print(np.percentile(array,25,axis=0))
print("25th percentile row wise")
print(np.percentile(array,25,axis=1))

print("50th percentile column wise")
print(np.percentile(array,50,axis=0))
print("50th percentile row wise")
print(np.percentile(array,50,axis=1))

print("75th percentile column wise")
print(np.percentile(array,75,axis=0))
print("75th percentile row wise")
print(np.percentile(array,75,axis=1))

print("mean of each col of array is",np.mean(array,axis=0))
print("mean of each row of array is",np.mean(array,axis=1))

print("median of each col of array is",np.median(array,axis=0))
print("median of each row of array is",np.median(array,axis=1))

print("standard deviation of each col of array is",np.std(array,axis=0))
print("standard deviation of each row of array is",np.std(array,axis=1))

the absolute value element wise:
[[1 2 3]
 [4 5 6]]
25th percentile column wise
[-2.75 -0.25 -3.75]
25th percentile row wise
[-0.5 -5. ]
50th percentile column wise
[-1.5  1.5 -1.5]
50th percentile row wise
[ 1. -4.]
75th percentile column wise
[-0.25  3.25  0.75]
75th percentile row wise
[2.  0.5]
mean of each col of array is [-1.5  1.5 -1.5]
mean of each row of array is [ 0.66666667 -1.66666667]
median of each col of array is [-1.5  1.5 -1.5]
median of each row of array is [ 1. -4.]
standard deviation of each col of array is [2.5 3.5 4.5]
standard deviation of each row of array is [2.05480467 4.78423336]


In [ ]:
#q2 b
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print("floor of array are",np.floor(a))
print("ceil of array are",np.ceil(a))
print("truncated array are",np.trunc(a))
print("rounded array are",np.round(a))

floor of array are [-2. -2. -1.  0.  1.  1.  3.]
ceil of array are [-1. -1. -0.  1.  2.  2.  3.]
truncated array are [-1. -1. -0.  0.  1.  1.  3.]
rounded array are [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#q3 a
array=np.array([10,52,62,16,16,54,453])
n=array.size
array1=np.sort(array)
print("sorted array is ",array1)
print("indices of sorted array is",np.argsort(array))
print("4 smallest element are ",array1[:4])
print("5 largest value are",array1[-5:])

sorted array is  [ 10  16  16  52  54  62 453]
indices of sorted array is [0 3 4 1 5 2 6]
4 smallest element are  [10 16 16 52]
5 largest value are [ 16  52  54  62 453]


In [ ]:
#q3 b
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print("integer elements are:")
inta=array[array==array.astype(int)]
print(inta)

print("float elements are:")
intf=array[array!=array.astype(int)]
print(intf)



integer elements are:
[1. 2. 3. 2.]
float elements are:
[1.2 2.2]


In [ ]:
#q4 a
import cv2
img = cv2.imread('/content/joshua-aragon-FGXqbqbGt5o-unsplash.jpg')
print(img.shape)
# cv2.imshow('hello', img)
f = open('/content/img_txt', 'x')

#print(np.array_str(img))
f.write(np.array_str(img))
f.close()




(1826, 2746, 3)


FileExistsError: ignored

In [ ]:
print(img)

[[[15  6 19]
  [16  7 20]
  [17  8 21]
  ...
  [65 63 75]
  [64 62 74]
  [65 63 75]]

 [[16  7 20]
  [17  8 21]
  [18  9 22]
  ...
  [63 61 73]
  [64 62 74]
  [65 63 75]]

 [[17  8 21]
  [17  8 21]
  [18  9 22]
  ...
  [64 60 72]
  [60 58 70]
  [62 60 72]]

 ...

 [[18 11 14]
  [18 11 14]
  [18 11 14]
  ...
  [20 10 10]
  [20 10 10]
  [20 10 10]]

 [[18 11 16]
  [19 12 17]
  [19 12 17]
  ...
  [21 11 11]
  [18  8  8]
  [19  9  9]]

 [[18 11 16]
  [19 12 17]
  [19 12 17]
  ...
  [21 11 11]
  [19  9  9]
  [20 10 10]]]


In [ ]:
def img_to_array(path):
  import keras
  from keras.preprocessing.image import load_img

  img = load_img(path)
  print(type(img))
  print(img.format)
  print(img.mode)
  print(img.size)
  img.show()

  # resizing image
  imgr = img.resize([30, 30])
  print(imgr.size)

  # converting image to array
  from keras.preprocessing.image import img_to_array
  imgarr = img_to_array(img)
  print(imgarr.shape)

  # saving image
  from keras.preprocessing.image import save_img
  save_img('corvette_color.jpg', imgarr)

  # converting to grayscale 
  # img_gray = load_img(path, grayscale = True)
  # img_gray_arr = img_to_array(img_gray)
  # save_img('corvette_grayscale.jpg', img_gray_arr)


address = '/content/joshua-aragon-FGXqbqbGt5o-unsplash.jpg'
img_to_array(address)

<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(2746, 1826)
(30, 30)
(1826, 2746, 3)
